#!/bin/bash
file_name="\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)"
file_name=$(echo "$file_name" | sed 's/\*/\\\\*/g; s/"/\\"/g; s/\$/\\\$/g; s/\?/\\\?/g')
touch "$file_name"
echo "Best School" >> "$file_name"
close "$file_name"
